BOX_IMAGE = "mysql8-centos7-3"
NODE_IP_NW = "192.168.0."
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = BOX_IMAGE
  
  (1..NODE_COUNT).each do |i|
      config.vm.define "node#{i}" do |subconfig|
		subconfig.vm.box_check_update = false
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.network :private_network, ip: NODE_IP_NW + "#{i + 10}"
		subconfig.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--cpus", "2"]
			vb.customize ["modifyvm", :id, "--memory", "2048"]
		end
      end
  end
end
